# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tea Drinking Development
tagline:          'I''d drink code, too, if that was a thing.'
description:      'TDD'
url:              http://TeaDrivenDev.github.io

author:
  name:           'TeaDrivenDev'
  url:            https://twitter.com/TeaDrivenDev

paginate:         5

# Custom vars
version:          1.0.3

github:
  repo:           https://github.com/TeaDrivenDev/TeaDrivenDev.github.io
